debug

diff --git a/.github/workflows/create.yml b/.github/workflows/create.yml
--- a/.github/workflows/create.yml
+++ b/.github/workflows/create.yml
@@ -161,8 +161,29 @@ jobs:
         env:
           TF_OUTPUTS: ${{ steps.tf-outputs.outputs.tf_outputs }}
         run: |
+          set -e
+          echo "Starting Update ECS Task Definition step"
+          
+          echo "Environment variables:"
+          env | grep -E "TF_VAR_|AWS_|NODE_ENV|GITHUB_ENV"
+          
+          echo "Retrieving ECR Repository URL"
           ECR_REPO_URL=$(echo '${{ steps.tf-outputs.outputs.tf_outputs }}' | jq -r '.ecr_repository_url.value')
-          TASK_DEF=$(aws ecs describe-task-definition --task-definition credex-core-$TF_VAR_environment --query taskDefinition)
+          echo "ECR Repository URL: $ECR_REPO_URL"
+          
+          echo "Describing ECS task definition"
+          TASK_DEF_NAME="credex-core-$TF_VAR_environment"
+          echo "Task Definition Name: $TASK_DEF_NAME"
+          
+          TASK_DEF=$(aws ecs describe-task-definition --task-definition $TASK_DEF_NAME --query taskDefinition)
+          if [ $? -ne 0 ]; then
+            echo "Error describing task definition. AWS CLI output:"
+            aws ecs describe-task-definition --task-definition $TASK_DEF_NAME
+            exit 1
+          fi
+          echo "Task Definition retrieved successfully"
+          
+          echo "Updating task definition"
           NEW_TASK_DEF=$(echo $TASK_DEF | jq --arg ECR_REPO_URL "$ECR_REPO_URL" '.containerDefinitions[0].image = $ECR_REPO_URL + ":latest" | .containerDefinitions[0].environment += [
             {"name": "NEO_4J_LEDGER_SPACE_BOLT_URL", "value": "${{ env.TF_VAR_neo4j_ledger_space_bolt_url }}"},
             {"name": "NEO_4J_SEARCH_SPACE_BOLT_URL", "value": "${{ env.TF_VAR_neo4j_search_space_bolt_url }}"},
@@ -173,8 +194,19 @@ jobs:
             {"name": "JWT_SECRET", "value": "${{ vars.JWT_SECRET }}"},
             {"name": "OPEN_EXCHANGE_RATES_API", "value": "${{ vars.OPEN_EXCHANGE_RATES_API }}"}
           ]')
+          echo "Task definition updated"
+          
+          echo "Writing new task definition to file"
           echo $NEW_TASK_DEF > new-task-def.json
+          
+          echo "Registering new task definition"
           aws ecs register-task-definition --cli-input-json file://new-task-def.json
+          if [ $? -ne 0 ]; then
+            echo "Error registering new task definition. Contents of new-task-def.json:"
+            cat new-task-def.json
+            exit 1
+          fi
+          echo "New task definition registered successfully"
 
       - name: Deploy Application
         env:
